
# html lang
language: en

# header

menu:
  Home: /
  Posts: /archives/
  About: /about/

# stylesheets loaded in the <head>
stylesheets:
- /css/style.css

# scripts loaded in the end of the body
scripts:
- /js/frame.js

# favicon
favicon: /favicon.ico

date_format: D MMM YYYY

# profile
profile:
  title: Howdy! It's Tripovich! 
  body: This micro blog is the showcase of my work on game music. There are sketches and loops in the posts section, have a listen. Contact email on About page. I'm looking to collaborate with beginner game developers free of charge.
  image: /profile_cover.png

  links:
    Posts: /archives/
    Soundcloud: https://soundcloud.com/tripovich


# footer
footer:
  copyright_info:
    enable: false
    author:

  powered_by: # Powered by Hexo & Frame
    enable: false

  other_info:
    enable: false
    content:

# color mode: default / classic / dark
color_mode: default

# mathjax setting
# note: need to install the hexo plugin for math: https://github.com/hexojs/hexo-math
mathjax_enable: false
